inherit_from: .rubocop_todo.yml
require:
  - rubocop-performance
  - rubocop-rails
AllCops:
  TargetRubyVersion: 2.6.0
  DisplayCopNames: true
  Exclude:
    - bin/*
    - vendor/ruby/**/*
    - vendor/bundle/**/*
    - node_modules/**/*
    - db/schema.rb
    - .licenses/**/*
Rails:
  Enabled: true
Rails/UnknownEnv:
  Environments:
    - production
    - staging
    - development
    - test
Metrics:
  Exclude:
    - db/migrate/*
    - Rakefile
    - Gemfile
    - config/**/*
    - spec/**/*
    - lib/tasks/**/*
Metrics/BlockLength:
  Exclude:
    - config/environments/*
    - lib/tasks/**/*
    - spec/**/*
Layout:
  Exclude:
    - config/environments/*
Style:
  Exclude:
    - spec/*_helper.rb
Style/BlockComments:
  Exclude:
    - config/**/*
    - spec/**/*
Style/Documentation:
  Enabled: false
