inherit_from: .rubocop_todo.yml
AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.4
  Include:
    - Rakefile
    - config.ru
    - lib/**/*.rake
  Exclude:
    - node_modules/**/*
    - db/*
    - vendor/ruby/**/*
    - config/initializers/simple_form_bootstrap.rb
    - node_modules/**/*
Rails:
  Enabled: true
Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb
Style/FileName:
  Exclude:
    - Gemfile
    - Capfile
