export const RECEIVE_ATTENDEES = 'RECEIVE_ATTENDEES';
export const RECEIVE_CHECK_POINTS = 'RECEIVE_CHECK_POINTS';

export const SUMMARY_UPDATE = 'SUMMARY_UPDATE';
export const REGISTER_UPDATE = 'REGISTER_UPDATE';

export const SUMMARY_INTERVAL = 300;
export const REALTIME_INTERVAL = 10;

export default RECEIVE_ATTENDEES;
