export const RECEIVE_ACCESS_RECORDS = 'RECEIVE_ACCESS_RECORDS';
export const ACCESS_RECORD_UPDATE = 'ACCESS_RECORD_UPDATE';
export const ACCESS_RECORD_SET = 'ACCESS_RECORD_SET';
export const REQUEST_ACCESS = 'REQUEST_ACCESS';
export const CANCEL_REQUEST = 'CANCEL_REQUEST';
export const ACCESS_UPDATE = 'ACCESS_UPDATE';
export const REJECT_REQUEST = 'REJECT_REQUEST';
export const ACCEPT_REQUEST = 'ACCEPT_REQUEST';

export default RECEIVE_ACCESS_RECORDS;
