export const RECEIVE_ACCESS_RECORDS = 'RECEIVE_ACCESS_RECORDS';
export const ACCESS_RECORD_UPDATE = 'ACCESS_RECORD_UPDATE';
export const ACCESS_RECORD_SET = 'ACCESS_RECORD_SET';

export default RECEIVE_ACCESS_RECORDS;
