export const RECEIVE_ATTENDEES = 'RECEIVE_ATTENDEES';

export const REGISTER = 'REGISTER';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const START_REGISTER = 'START_REGISTER';
export const CANCEL_REGISTER = 'CANCEL_REGISTER';

export default RECEIVE_ATTENDEES;
