export const RECEIVE_CHECK_RECORDS = 'RECEIVE_CHECK_RECORDS';

export const REGISTER = 'REGISTER';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_UPDATE = 'REGISTER_UPDATE';
export const START_REGISTER = 'START_REGISTER';
export const CANCEL_REGISTER = 'CANCEL_REGISTER';

export default RECEIVE_CHECK_RECORDS;
