export const RECEIVE_CHECK_RECORDS = 'RECEIVE_CHECK_RECORDS';
export const CHECK_RECORD_UPDATE = 'CHECK_RECORD_UPDATE';
export const CHECK_RECORD_SET = 'CHECK_RECORD_SET';


export default RECEIVE_CHECK_RECORDS;
